import turtle
from turtle import *
color('black')
begin_fill()
pensize(3)
left(50)
forward(133)
circle(50,200)
right(140)
circle(50,200)
forward(133)
style = ('Courier', 90, 'normal')
turtle.write('PRATIBHA', font=style, align='center')
end_fill()
done()